---
apiVersion: v1
kind: Namespace
metadata:
  name: "appmesh-ns"
  labels:
    mesh: appmesh-mesh
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
    gateway: ingress-gw
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: Mesh
metadata:
  name: appmesh-mesh
spec:
  namespaceSelector:
    matchLabels:
      mesh: appmesh-mesh
